"""
speech_performance.py
Converts raw NPC dialogue (already generated by rpe_llm_service /
rpe_npc_service — see that module's json_schema_task for the "dialogue"
field this consumes) into speech-ready delivery metadata, upstream of and
independent from any specific TTS provider:

    NPC backend response -> SpeechPerformanceService -> speechText +
    delivery metadata -> TTSManager -> selected provider -> audio

Deliberately provider-agnostic: this module only ever returns a speed
*multiplier* and pause durations, never a voice name or an absolute speed —
each provider (Chirp 3 HD today; any future local provider) has its own
voice namespace and default speed, resolved by TTSManager/the provider
itself, not here.

Deterministic only — no second LLM call, no rewriting of words. This may
only adjust *how* the existing text is spoken (speed, pause padding around
it) and light punctuation/whitespace normalization for natural TTS pacing.
It must never add, remove, or reword content — the transcript shown to the
user always comes from the original `text` (displayText), never from
anything this module returns (speechText is TTS-only).
"""
import re

# Starting values per the emotion values rpe_emotion_service already emits
# (see EMOTION_TO_MOOD in RolePlaySessionV2.jsx for the same set on the
# frontend side) — kept in this one place so tuning doesn't touch any
# provider or the router. Not claimed to be final/validated; revisit after
# a real voice-quality comparison pass.
EMOTION_SPEECH_PARAMS = {
    "neutral":    {"speed_multiplier": 1.00, "pause_multiplier": 1.00},
    "frustrated": {"speed_multiplier": 1.05, "pause_multiplier": 0.80},
    "concerned":  {"speed_multiplier": 0.94, "pause_multiplier": 1.20},
    "satisfied":  {"speed_multiplier": 0.98, "pause_multiplier": 1.05},
    "confident":  {"speed_multiplier": 0.99, "pause_multiplier": 1.05},
    "happy":      {"speed_multiplier": 1.02, "pause_multiplier": 0.95},
    "surprised":  {"speed_multiplier": 1.03, "pause_multiplier": 0.90},
    "skeptical":  {"speed_multiplier": 0.97, "pause_multiplier": 1.10},
    "angry":      {"speed_multiplier": 1.08, "pause_multiplier": 0.75},
    "sad":        {"speed_multiplier": 0.92, "pause_multiplier": 1.25},
    "thinking":   {"speed_multiplier": 0.95, "pause_multiplier": 1.15},
}
_DEFAULT_PARAMS = EMOTION_SPEECH_PARAMS["neutral"]

BASE_PAUSE_BEFORE_MS = 150
BASE_PAUSE_AFTER_MS = 250

_ELLIPSIS_RE = re.compile(r"\.{2,}")
_WHITESPACE_RE = re.compile(r"[ \t]+")


def build_speech_performance(text: str, emotion: str = "neutral",
                              intensity: float | None = None) -> dict:
    """
    text: the NPC's original dialogue line (displayText) — never modified
    in meaning, only whitespace/punctuation-normalized for natural TTS
    pacing.
    emotion: one of rpe_emotion_service's existing values; unknown values
    fall back to the neutral profile rather than raising.
    intensity: optional 0..1 escalation/trust-derived scalar that nudges
    pacing further within the emotion's own range — omitted (None) leaves
    the emotion's base multipliers untouched.

    Returns {speechText, speedMultiplier, emotion, pauseBeforeMs, pauseAfterMs}.
    speedMultiplier is applied by the caller on top of whichever provider's
    own base speed/voice is in play — this module never picks a voice.
    """
    speech_text = _normalize_pacing(text or "")
    params = EMOTION_SPEECH_PARAMS.get(emotion, _DEFAULT_PARAMS)

    speed_multiplier = params["speed_multiplier"]
    pause_multiplier = params["pause_multiplier"]
    if intensity is not None:
        # Intensity nudges up to +/-8% around the emotion's own multiplier —
        # a small, bounded adjustment, never enough to override the emotion
        # mapping itself.
        clamped = max(0.0, min(1.0, intensity))
        nudge = (clamped - 0.5) * 0.16
        speed_multiplier += nudge
        pause_multiplier -= nudge

    return {
        "speechText": speech_text,
        "speedMultiplier": round(speed_multiplier, 3),
        "emotion": emotion,
        "pauseBeforeMs": round(BASE_PAUSE_BEFORE_MS * pause_multiplier),
        "pauseAfterMs": round(BASE_PAUSE_AFTER_MS * pause_multiplier),
    }


def _normalize_pacing(text: str) -> str:
    """
    Whitespace/punctuation cleanup only — never touches words. Collapses
    runs of spaces, and turns a bare "..." into a single ellipsis char so
    a provider's own clause-pause handling treats it as one pause point
    rather than three periods in a row (which reads as three short
    sentence-end pauses instead of one longer one).
    """
    normalized = _WHITESPACE_RE.sub(" ", text.strip())
    normalized = _ELLIPSIS_RE.sub("…", normalized)
    return normalized
