import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Brain, Zap, MessageSquare, ArrowRight } from 'lucide-react';
import { fadeInUp, staggerContainer } from '@/lib/animations';

const FEATURES = [
  {
    icon: Brain,
    title: 'Personality assessment',
    description:
      'Answer 44 scientifically validated questions from the Big Five Inventory. Understand your OCEAN profile in minutes.',
  },
  {
    icon: Zap,
    title: 'Adaptive scenarios',
    description:
      'Every training scenario is generated by AI specifically for your personality. Introverts and extroverts get completely different experiences.',
  },
  {
    icon: MessageSquare,
    title: 'Real-time feedback',
    description:
      'Receive live coaching on your tone, pacing, and presence — not after the session, but while it’s happening.',
  },
];

const STEPS = [
  ['Survey', 'Build profile'],
  ['Baseline', 'Voice signal'],
  ['Practice', 'Live role-play'],
  ['Insight', 'Coach review'],
];

export default function Landing() {
  return (
    <div
      style={{
        position: 'relative',
        minHeight: '100vh',
        background: 'var(--bg-canvas)',
        color: 'var(--text-primary)',
      }}
    >
      {/* Top bar */}
      <header
        style={{
          position: 'relative',
          zIndex: 10,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '20px 24px',
          maxWidth: 1180,
          margin: '0 auto',
        }}
      >
        <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 10 }} aria-label="EmpowerZ home">
          <div className="sb-mark" style={{ width: 28, height: 28, fontSize: 14 }}>EZ</div>
          <span className="sb-brand-text">EmpowerZ</span>
        </Link>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Link to="/signin" className="btn btn-ghost"><span className="btn-label">Sign in</span></Link>
          <Link to="/signup" className="btn btn-primary"><span className="btn-label">Get started</span></Link>
        </div>
      </header>

      {/* Hero */}
      <section
        className="violet-halo"
        style={{
          position: 'relative',
          maxWidth: 980,
          margin: '0 auto',
          padding: '60px 24px 40px',
        }}
      >
        <motion.div variants={staggerContainer} initial="initial" animate="animate" style={{ display: 'flex', flexDirection: 'column', gap: 22 }}>
          <motion.div variants={fadeInUp}>
            <span className="t-over" style={{ color: 'var(--accent)' }}>EmpowerZ · v0.4 · research preview</span>
          </motion.div>

          <motion.h1 variants={fadeInUp} className="t-display" style={{ maxWidth: 820 }}>
            Train soft skills the way your{' '}
            <span style={{ background: 'var(--gradient-accent)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent' }}>
              mind learns.
            </span>
          </motion.h1>

          <motion.p
            variants={fadeInUp}
            style={{
              fontSize: 18,
              color: 'var(--text-secondary)',
              maxWidth: 620,
              lineHeight: 1.55,
              margin: 0,
            }}
          >
            Adaptive AI training that profiles your personality, runs role-play simulations with a live NPC,
            and gives you precise, multimodal feedback on what you actually did.
          </motion.p>

          <motion.div variants={fadeInUp} style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginTop: 8 }}>
            <Link to="/signup" className="btn btn-primary btn-lg">
              <span className="btn-label" style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
                Get started free
                <ArrowRight size={16} strokeWidth={1.8} />
              </span>
            </Link>
            <Link to="/signin" className="btn btn-secondary btn-lg">
              <span className="btn-label">Sign in</span>
            </Link>
          </motion.div>

          <motion.div variants={fadeInUp} className="t-cap">
            44 scientifically validated questions from the Big Five Inventory · ~5 min · No right answers
          </motion.div>
        </motion.div>
      </section>

      {/* Feature cards */}
      <section style={{ position: 'relative', maxWidth: 1180, margin: '0 auto', padding: '32px 24px' }}>
        <motion.div
          variants={staggerContainer}
          initial="initial"
          whileInView="animate"
          viewport={{ once: true, margin: '-60px' }}
          className="grid-3 stagger"
          style={{ gap: 16 }}
        >
          {FEATURES.map(({ icon: Icon, title, description }) => (
            <motion.div key={title} variants={fadeInUp} className="card">
              <div
                style={{
                  width: 32,
                  height: 32,
                  borderRadius: 8,
                  background: 'var(--accent-soft)',
                  border: '1px solid var(--accent-muted)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: 'var(--accent)',
                  marginBottom: 16,
                }}
              >
                <Icon size={16} strokeWidth={1.6} />
              </div>
              <div className="t-h3" style={{ marginBottom: 6 }}>{title}</div>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', margin: 0, lineHeight: 1.55 }}>
                {description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* How it works */}
      <section style={{ position: 'relative', maxWidth: 1180, margin: '0 auto', padding: '16px 24px 64px' }}>
        <div className="card" style={{ padding: 32 }}>
          <div className="t-over" style={{ marginBottom: 24 }}>How it works</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', alignItems: 'center', gap: 0 }}>
            {STEPS.map(([label, sub], i) => (
              <React.Fragment key={label}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '12px 8px' }}>
                  <div
                    className="score-num"
                    style={{
                      width: 36,
                      height: 36,
                      borderRadius: '50%',
                      background: 'var(--bg-input)',
                      border: '1px solid var(--border-subtle)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      color: 'var(--accent)',
                      fontSize: 13,
                    }}
                  >
                    {String(i + 1).padStart(2, '0')}
                  </div>
                  <div>
                    <div className="fg" style={{ fontWeight: 500 }}>{label}</div>
                    <div className="t-cap">{sub}</div>
                  </div>
                </div>
                {i < STEPS.length - 1 && (
                  <div style={{ height: 1, background: 'var(--border-subtle)', display: 'none' }} className="hide-on-mobile" />
                )}
              </React.Fragment>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer
        style={{
          position: 'relative',
          borderTop: '1px solid var(--border-subtle)',
          padding: '20px 24px',
          maxWidth: 1180,
          margin: '0 auto',
          display: 'flex',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: 12,
        }}
      >
        <span className="t-cap">EmpowerZ · A SLIIT Research Project · 2026</span>
        <div style={{ display: 'flex', gap: 18 }}>
          <span className="t-cap">Research</span>
          <span className="t-cap">Privacy</span>
          <span className="t-cap">Contact</span>
        </div>
      </footer>
    </div>
  );
}
