import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Brain, Zap, MessageSquare, ArrowRight } from 'lucide-react';
import BackgroundGradient from '@/components/ui/background-gradient';
import Logo from '@/components/ui/logo';
import { fadeInUp, staggerContainer } from '@/lib/animations';

const features = [
  {
    icon: Brain,
    title: 'Personality assessment',
    description:
      'Answer 44 scientifically validated questions from the Big Five Inventory. Understand your OCEAN profile in minutes.',
  },
  {
    icon: Zap,
    title: 'Adaptive scenarios',
    description:
      'Every training scenario is generated by AI specifically for your personality. Introverts and extroverts get completely different experiences.',
  },
  {
    icon: MessageSquare,
    title: 'Real-time feedback',
    description:
      'Receive live coaching on your tone, pacing, and presence — not after the session, but while its happening.',
  },
];

export default function Landing() {
  return (
    <div className="relative min-h-screen bg-background text-foreground">
      <BackgroundGradient />

      {/* Nav */}
      <header className="relative z-10 flex items-center justify-between px-6 py-5 max-w-6xl mx-auto">
        <Logo size="md" />
        <div className="flex items-center gap-3">
          <Link
            to="/signin"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors px-3 py-1.5"
          >
            Sign in
          </Link>
          <Link
            to="/signup"
            className="text-sm bg-primary text-primary-foreground rounded-lg px-4 py-1.5 hover:bg-primary/90 transition-colors font-medium"
          >
            Get started
          </Link>
        </div>
      </header>

      {/* Hero */}
      <section className="relative z-10 flex flex-col items-center text-center px-6 pt-20 pb-24 max-w-4xl mx-auto">
        <motion.div
          variants={staggerContainer}
          initial="initial"
          animate="animate"
          className="space-y-6"
        >
          <motion.div variants={fadeInUp}>
            <span className="inline-flex items-center gap-2 rounded-full border border-border/60 bg-muted/50 px-3 py-1 text-xs text-muted-foreground">
              Research project · SLIIT
            </span>
          </motion.div>

          <motion.h1
            variants={fadeInUp}
            className="text-4xl sm:text-5xl md:text-[3.4rem] font-semibold tracking-tight leading-[1.15] text-foreground"
          >
            Train soft skills with an{' '}
            <span className="bg-gradient-to-r from-violet-600 to-indigo-500 bg-clip-text text-transparent">
              AI that adapts to you
            </span>
          </motion.h1>

          <motion.p
            variants={fadeInUp}
            className="max-w-xl mx-auto text-base sm:text-lg text-muted-foreground leading-relaxed"
          >
            Your personality shapes how you learn. Our platform reads your OCEAN
            profile and builds interview, negotiation, and speaking scenarios
            designed specifically for who you are.
          </motion.p>

          <motion.div
            variants={fadeInUp}
            className="flex flex-col sm:flex-row items-center justify-center gap-3 pt-2"
          >
            <Link
              to="/signup"
              className="group flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-6 py-3 text-sm font-medium hover:bg-primary/90 transition-all duration-200 hover:gap-3"
            >
              Get started free
              <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" />
            </Link>
            <Link
              to="/signin"
              className="rounded-lg border border-border bg-background text-foreground px-6 py-3 text-sm font-medium hover:bg-muted transition-colors"
            >
              Sign in
            </Link>
          </motion.div>
        </motion.div>
      </section>

      {/* Feature cards */}
      <section className="relative z-10 max-w-5xl mx-auto px-6 pb-24">
        <motion.div
          variants={staggerContainer}
          initial="initial"
          whileInView="animate"
          viewport={{ once: true, margin: '-60px' }}
          className="grid grid-cols-1 sm:grid-cols-3 gap-5"
        >
          {features.map(({ icon: Icon, title, description }) => (
            <motion.div
              key={title}
              variants={fadeInUp}
              className="rounded-xl border border-border/60 bg-card/70 backdrop-blur-sm p-6 space-y-3"
            >
              <div className="inline-flex items-center justify-center w-9 h-9 rounded-lg bg-primary/10">
                <Icon className="size-4 text-primary" />
              </div>
              <h3 className="text-sm font-semibold text-foreground">{title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {description}
              </p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-border py-8 text-center text-xs text-muted-foreground">
        Adaptive Coach · Final-year research project · Not for commercial use
      </footer>
    </div>
  );
}
