"""create users and personality profiles

Revision ID: b96927ee964d
Revises: 20260502_001
Create Date: 2026-05-03 15:14:06.752407

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b96927ee964d'
down_revision: Union[str, None] = '20260502_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('personality_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('openness', sa.Float(), nullable=False),
    sa.Column('conscientiousness', sa.Float(), nullable=False),
    sa.Column('extraversion', sa.Float(), nullable=False),
    sa.Column('agreeableness', sa.Float(), nullable=False),
    sa.Column('neuroticism', sa.Float(), nullable=False),
    sa.Column('raw_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('agreeableness BETWEEN 0.0 AND 100.0', name='ck_agreeableness_range'),
    sa.CheckConstraint('conscientiousness BETWEEN 0.0 AND 100.0', name='ck_conscientiousness_range'),
    sa.CheckConstraint('extraversion BETWEEN 0.0 AND 100.0', name='ck_extraversion_range'),
    sa.CheckConstraint('neuroticism BETWEEN 0.0 AND 100.0', name='ck_neuroticism_range'),
    sa.CheckConstraint('openness BETWEEN 0.0 AND 100.0', name='ck_openness_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personality_profiles_user_id'), 'personality_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personality_profiles_user_id'), table_name='personality_profiles')
    op.drop_table('personality_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
